reference/javascript/javascript-support.md
=> small typo in plugin docs

tutorials/how-to-style-text/index.md
corrected styleRange to styleRanges
=> docs changed due to mistake in api usage

distribution/how-to-submit-to-plugin-manager.md, distribution/options.md, distribution/packaging.md, reference/structure/manifest.md, xdpegs/1-performance.md, xdpegs/2-scenegraph.md, xdpegs/3-network-io.md, xdpegs/4-file-io.md, xdpegs/5-ui.md
This updates the documentation with some more clarity around common causes of plugin rejection in the Plugin Manager.
Note: there's a lot of diffs in the xdpegs, since I needed to fix some formatting. There's only a couple of changes to section 5.13 Menus (Added to 5.13.6 and created 5.13.7)
Please review and suggest any changes.
=> More info for common rejection reasons

tutorials/quick-start-react/index.md
=> Quickstart react

tutorials/how-to-integrate-with-OAuth/index.md
Fixed typos on https://adobexdplatform.com/plugin-docs/tutorials/how-to-integrate-with-OAuth page
=> Fixed typos.

changes.md, known-issues.md, reference/ui/elements/checkboxes.md, reference/ui/elements/dropdowns.md, reference/ui/elements/textfields.md, reference/ui/styles/using-css.md
Add fixes and improvements from the UI and UXP API layer.
=> Bug fixes and improvements for XD 18

reference/interactions.md, reference/scenegraph.md
=> Xd 19 apis

reference/interactions.md
Fixing a few mistakes in the new `interactions` module docs and did some enhancements (keeping the docs for this new module consistent with previous ones by keeping naming conventions for native JS types lowercase).
=> Interactions fix

reference/structure/manifest.md
=> manifest change - an additional size added

plugin-design-guidelines/ui_resources/index.md
=> updated the styling for the UI index page

tutorials/how-to-draw-lines/index.md
=> Fixed improper numbering in main function code.

distribution/how-to-submit-to-plugin-manager.md
=> how-to-submit-to-plugin-manager.md: typo

distribution/submission-checklist.md
A more thorough and up-to-date checklist for developers before submitting plugins to Adobe for review.
=> Submission checklist added.

reference/xd-index.md
There is a typo in the reference link. See Issue #209
=> fix link typo

reference/application.md
=> Xd 25 apis

changes.md, known-issues.md, reference/scenegraph.md, tutorials/debugging/index.md
=> Xd 26 apis

CONTRIBUTING.md, README.md, distribution/how-to-create-deep-links.md, distribution/how-to-submit-to-plugin-manager.md, distribution/packaging.md, distribution/submission-checklist.md, public/header.html, reference/structure/manifest.md, tutorials/quick-start-panel/index.md, tutorials/quick-start-react/index.md, tutorials/quick-start/index.md
- [X ] I have signed the [Adobe CLA](http://adobe.github.io/cla.html) (required).
- [ X] Something new that I have already discussed with Adobe in a GitHub issue. Issue link:
Updating the URLs to the console was required because the site architecture changed.
=> Update Console links, revise instructions for plugin devs

SUMMARY.md, changes.md, known-issues.md, reference/ImageFill.md, reference/PerPluginStorage.md, reference/scenegraph.md
=> XD 29 docs changes

changes.md, reference/core/automatic-cleanups.md, reference/scenegraph.md
=> XD 30 docs changes

changes.md, reference/interactions.md, reference/scenegraph.md
=> Xd 32 docs

changes.md, reference/interactions.md, reference/scenegraph.md
=> Xd 33 docs

changes.md, reference/scenegraph.md
=> Xd 34 docs
